version: "3"
services:

 db:
  image: postgres:latest
  restart: unless-stopped
  container_name: database
  env_file:
   - .env
  networks:
   - backend_network

 webapp:
  build: ./back
  container_name: webapp
  restart: unless-stopped
  ports:
   - "8000:8000"
  env_file:
   - .env
  depends_on:
   - db
  links:
   - db:db
  volumes:
   - ./back:/back
  entrypoint: "bash /back/docker-entrypoint.sh"
  command: "runserver 0.0.0.0:8000"
  networks: 
   - nginx_network
   - backend_network

 front:
  build: ./front
  container_name: front
  volumes:
   - './front:/app'
   - '/app/node_modules'
  ports:
   - '8081:8080'
  networks:
   - nginx_network
  depends_on:
   - db

networks:
 nginx_network:
  driver: bridge
 backend_network:
  driver: bridge
