version: "3"
services:

 db:
  image: postgres:latest
  restart: unless-stopped
  container_name: database
  env_file:
   - .env

 webapp:
  build: ./back
  container_name: webapp
  restart: unless-stopped
  ports:
   - "8000:8000"
  env_file:
   - .env
  depends_on:
   - db
   - redis
  links:
   - db:db
  volumes:
   - ./back:/back
  entrypoint: "bash /back/docker-entrypoint.sh"
  command: "runserver 0.0.0.0:8000"

 redis:
  image: redis:alpine
  container_name: redis

 celery:
  container_name: celery
  restart: always
  build: ./back
  entrypoint: "celery -A config worker -l info"
  volumes:
   - ./back:/back
  env_file:
   - .env
  depends_on:
   - db
   - redis
   - webapp

 celery-beat:
  container_name: celery-beat
  restart: always
  build: ./back
  entrypoint: "celery -A config beat -l info"
  volumes:
   - ./back:/back
  env_file:
   - .env
  depends_on:
   - db
   - redis
   - webapp

 front:
  build: ./front
  container_name: front
  volumes:
   - './front:/app'
   - '/app/node_modules'
  ports:
   - '8081:8080'
  depends_on:
   - webapp

 prometheus:
  image: prom/prometheus:v2.14.0
  container_name: prometheus
  depends_on:
   - webapp
  volumes:
   - './prometheus.yml:/etc/prometheus/prometheus.yml'
  network_mode: host
 
 grafana:
  image: grafana/grafana:6.5.2
  container_name: grafana
  depends_on:
   - prometheus
  ports:
   - '3060:3000'
  network_mode: host
