# Generated by Django 3.2.7 on 2021-09-05 19:00

import cars.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.slugs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)], verbose_name='Cost')),
                ('date_start', models.DateTimeField(validators=[cars.validators.no_past_validator], verbose_name='Start date')),
                ('date_finish', models.DateTimeField(validators=[cars.validators.no_past_validator], verbose_name='Finish date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('slug', models.CharField(db_index=True, default=utils.slugs.generate_slug, editable=False, max_length=10, unique=True, verbose_name='Slug')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carpart')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
